version: '3'
services:
  my-app:
    image: my-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"